export interface CarrierMetrics {
    id: number;
    hos_compliance_above_threshold: boolean
    vehicle_maintenance_percentile: number
    substance_alcohol_at_alert: boolean
    unsafe_driving_above_threshold: boolean
    hm_compliance_percentile: number
    hos_compliance_measure: number
    hm_compliance_measure: number
    unsafe_driving_at_alert: boolean
    hos_compliance_at_alert: boolean
    carrier_id: number
    hm_compliance_at_alert: boolean
    crash_indicator_threshold: number
    driver_fitness_oos: number
    unsafe_driving_percentile: number
    driver_fitness_measure: number
    unsafe_driving_measure: number
    hos_compliance_threshold: number
    crash_indicator_at_alert: boolean
    driver_fitness_percentile: number
    vehicle_maintenance_above_threshold: boolean
    driver_fitness_at_alert: boolean
    carrier_score: number
    hos_compliance_oos: number
    hm_compliance_oos: number
    crash_indicator_percentile: number
    substance_alcohol_threshold: number
    hm_compliance_above_threshold: boolean
    vehicle_maintenance_measure: number
    hm_compliance_threshold: number
    crash_indicator_above_threshold: boolean
    driver_fitness_above_threshold: boolean
    hos_compliance_percentile: number
    unsafe_driving_oos: number
    vehicle_maintenance_threshold: number
    substance_alcohol_percentile: number
    substance_alcohol_oos: number
    crash_indicator_measure: number
    vehicle_maintenance_oos: number
    crash_indicator_oos: number
    unsafe_driving_threshold: number
    substance_alcohol_measure: number
    substance_alcohol_above_threshold: boolean
    driver_fitness_threshold: number
    vehicle_maintenance_at_alert: boolean
    updated_date?: any;
}
