export interface BrokersDetails {
    id: number;
    avg_days_to_pay: number
  broker_account_number: string
  broker_address_line1: string
  broker_address_line2: string
  broker_city: string
  broker_country: string
  broker_credit_limit: string
  broker_dot_number: string
  broker_ein_number: string
  broker_email: string
  broker_first_name: string
  broker_job_title: string
  broker_caption: string
  broker_last_name: string
  broker_logo: string
  broker_mc_number: string
  broker_phone_number: string
  broker_routing_number: string
  broker_state: string
  broker_status: string
  broker_timezone: string
  broker_user_name: string
  broker_website: string
  broker_zip_code: string
  company_address_line1: string
  company_address_line2: string
  company_city: string
  company_country: string
  company_email: string
  company_name: string
  company_phone_number: string
  company_state: string
  company_type: string
  company_zip_code: string
  credit_limit: number
  is_verified: boolean
  updated_date: string
  verified_status: string
  }
