import { VendorsDetails } from '~/models/accounting/vendors/vendorsDetails'

const vendors:Array<VendorsDetails> = [
  {
    id: 1,
    name: 'John',
    contact_name: 'Bill Sanders',
    email: 'samsara@gmail.com',
    phone_number: '532-215-3210',
    address_line1: '583 West Milton Road',
    address_line2: '2118 Thornridge Cir. Syracuse',
    state: 'California',
    city: 'Hawaii',
    zip_code: '34520',
    country: 'USA',
    business_hours: '09:00 - 18:00',
    line_of_business: 'Truck Leasing',
    status: 'Active',
    account_number: '903939393',
    bank_name: 'C.A',
    routing_number: '8393930303',
  },
  {
    id: 2,
    name: 'George Browns',
    contact_name: 'Chris Leonard',
    email: 'georgebrowns@gmail.com',
    phone_number: '536-945-1020',
    address_line1: '345 North Old Boulevard',
    address_line2: '3241 Cas. Hawaii',
    state: 'California',
    city: 'Los Angeles',
    zip_code: '14450',
    country: 'USA',
    business_hours: '09:00 - 18:00',
    line_of_business: 'Trailer Leasing',
    status: 'Inactive',
    account_number: '903939393',
    bank_name: 'B.C',
    routing_number: '8393930303',
  },
  {
    id: 3,
    name: 'Bill Sanders',
    contact_name: 'John Cameron',
    email: 'billsander@gmail.com',
    phone_number: '542-215-2571',
    address_line1: '4517 Washington Ave. Manchester, Kentucky',
    address_line2: '1048 Thornridge, Connecticut 35624',
    state: 'California',
    city: 'Anaheim',
    zip_code: '20145',
    country: 'USA',
    business_hours: '09:00 - 18:00',
    line_of_business: 'Trailer Leasing',
    status: 'In vocation',
    account_number: '705224515',
    bank_name: 'D.A',
    routing_number: '15284546',
  },
  {
    id: 4,
    name: 'John Ricardo',
    contact_name: 'John Williamson',
    email: 'johnricardo@gmail.com',
    phone_number: '546-625-4141',
    address_line1: '3241 Cas. Hawaii, Kentucky 32017',
    address_line2: '1950 Thornridge, Connecticut 42154',
    state: 'Illinois',
    city: 'Aurora',
    zip_code: '342540',
    country: 'USA',
    business_hours: '09:00 - 18:00',
    line_of_business: 'Truck Leasing',
    status: 'Active',
    account_number: '903939393',
    bank_name: 'A.C',
    routing_number: '743545559',
  }
]

export default vendors
