import { SafetyMetricsSummary } from '~/models/safetyMetrics/safetyMetricsSummary'

const safetyMetrics:Array<SafetyMetricsSummary> = [
  {
    id: 1,
    oos_hazmat_change_per: 10,
    crash_indicator_prev_month: 12,
    hm_compliance_change_per: 20,
    oos_driver_change_per: 22,
    substance_alcohol_prev_month: 29,
    carrier_id: 3,
    hos_compliance_prev_month: 30,
    oos_vehicle_prev_month: 8,
    oos_driver_curr_month: 9,
    hm_compliance_curr_month: 44,
    oos_vehicle_curr_month: 46,
    oos_hazmat_curr_month: 48,
    hos_compliance_curr_month: 36,
    hos_compliance_change_per: 37,
    crash_indicator_curr_month: 20,
    substance_alcohol_curr_month: 21,
    updated_date: '02-10-2022',
    crash_indicator_change_per: 56,
    oos_hazmat_prev_month: 25,
    oos_driver_prev_month: 47,
    substance_alcohol_change_per: 42,
    oos_vehicle_change_per: 41,
    hm_compliance_prev_month: 63,
    hm_compliance_oos: 10,
    crash_indicator_percentile: 11,
    vehicle_maintenance_percentile: 12,
    vehicle_maintenance_measure: 14,
    hm_compliance_percentile: 19,
    hos_compliance_measure: 30,
    hm_compliance_measure: 29,
    hos_compliance_percentile: 54,
    unsafe_driving_oos: 52,
    driver_fitness_oos: 51,
    substance_alcohol_percentile: 60,
    unsafe_driving_percentile: 6,
    driver_fitness_measure: 36,
    unsafe_driving_measure: 39,
    substance_alcohol_oos: 40,
    driver_fitness_percentile: 50,
    crash_indicator_measure: 41,
    vehicle_maintenance_oos: 13,
    crash_indicator_oos: 18,
    substance_alcohol_measure: 27,
    carrier_score: 15,
    hos_compliance_oos: 18
  }
]

export default safetyMetrics
