export interface YearlySummary {
    loads_nov: number
    revenue_may: number
    revenue_apr: number
    margin_jan: number
    loads_jan: number
    margin_nov: number
    loads_oct: number
    margin_oct: number
    loads_mar: number
    loads_sep: number
    margin_mar: number
    margin_sep: number
    loads_may: number
    margin_apr: number
    loads_apr: number
    revenue_aug: number
    margin_may: number
    current_balance: number
    revenue_dec: number
    revenue_jul: number
    margin_aug: number
    loads_aug: number
    total_loads: number
    revenue_feb: number
    revenue_jun: number
    broker_id: number
    loads_jul: number
    margin_feb: number
    margin_jun: number
    revenue_nov: number
    loads_feb: number
    loads_jun: number
    margin_jul: number
    loads_dec: number
    margin_dec: number
    total_revenue: number
    revenue_jan: number
    revenue_mar: number
    revenue_sep: number
    updated_date: string
    customer_id: number
    revenue_oct: number
  }
