export interface InvoicingDetails {
  id: number
  bill_to_address: string
  bill_to_name: string
  broker_id: number
  broker_name: string
  carrier_id: number
  carrier_name: string
  carrier_payment_status: string
  comments: string
  credit_terms: string
  customer_address: string
  customer_id: number
  customer_load_id: string
  customer_name: string
  customer_payment_status: string
  delivery_date: string
  delivery_location: string
  distance: number
  documents: {}
  driver_id: string
  driver_name: string
  gross_pay: number
  invoice_date: string
  invoice_status: string
  invoice_title: string
  line_items: string
  load_id: number
  load_weight: number
  notes: {}
  pickup_location: string
  reference_numbers: string
  remit_to_address: string
  revenue: number
  shipment_date: string
  total_amount_due: number
  updated_date: string
}
