export interface LoadsDetails {
    id: number
    accepted_date: string
    bol_number: string
    broker_id: number
    buy_now: number
    carrier_business_email: string
    carrier_dot_number: string
    carrier_id: number
    carrier_mc_number: string
    carrier_name: string
    carrier_phone_number: string
    co_driver_name: string
    commodity: string
    cust_ref_number: string
    delay_hours: string
    delivery_number: string
    dispatcher_email: string
    dispatcher_phone_number: string
    equipment: string
    load_cost: string
    load_delivery_date: string
    load_destination: string
    load_live_location: string
    load_mode: string
    load_origin: string
    load_pickup_date: string
    load_po_number: string
    load_status: string
    load_type: string
    loadboard: string
    main_driver_name: string
    miles: number
    rate: number
    segments: {}
    shipper_load_id: string
    shipper_name: string
    temperature: string
    total_distance: number
    total_revenue: number
    total_weight: string
    trailer_id: string
    trailer_required: boolean
    truck_id: string
    updated_date: string
  }
