import { StoreState } from "~/store";
import { AssetTransactionsDetailsState } from "~/store/accounting/assetTransactions";
import { AssetsDetailsState } from "~/store/accounting/assetsDetails";
import { BreakdownBrokerPaymentsDetailState } from "~/store/accounting/breakdownBrokerPending";
import { BrokerMetricsDetailsState } from "~/store/accounting/brokerMetricsDetails";
import { BrokerReviewsDetailsState } from "~/store/accounting/brokerReviewsDetails";
import { ContactsDetailsState } from "~/store/accounting/contactsDetails";
import { FactoringDetailsState } from "~/store/accounting/factoring";
import { FuelReportsState } from "~/store/accounting/fuelReport";
import { GenerateInvoiceDetailsState } from "~/store/accounting/generateInvoice";
import { InvoiceBoardDetailsState } from "~/store/accounting/invoiceBoard";
import { InvoicesDetailsState } from "~/store/accounting/invoices";
import { MileageReportsState } from "~/store/accounting/mileageReport";
import { OperationalTransactionsDetailsState } from "~/store/accounting/operationalPayments";
import { PayablePaymentSummaryState } from "~/store/accounting/payablePaymentSummary";
import { PayableSummaryState } from "~/store/accounting/payableSummary";
import { PayrollFinancialSummaryState } from "~/store/accounting/payrollFinancialSummary";
import { PayrollMetricsSummaryState } from "~/store/accounting/payrollMetricsSummary";
import { ReceivablesSummaryState } from "~/store/accounting/receivables";
import { ReceivedPaymentDetailsState } from "~/store/accounting/receivedPayment";
import { TaskDetailsState } from "~/store/accounting/taskDetails";
import { TollReportsState } from "~/store/accounting/tollReport";
import { VendorPaymentsDetailsState } from "~/store/accounting/vendorPayments";
import { VendorsDetailsState } from "~/store/accounting/vendors";
import { BrokerSummaryState } from "~/store/Broker/brokerSummary";
import { CarrierSalesLeadersState } from "~/store/Broker/carrierSalesLeadersDetails";
import { ContractRatesDetailsState } from "~/store/Broker/contractRates";
import { CustomerSalesLeadersState } from "~/store/Broker/customerSalesLeadersDetails";
import { CustomersDetailsState } from "~/store/Broker/customersDetails";
import { InvoicingDetailsState } from "~/store/Broker/invoicingDetails";
import { LoadHistoryDetailsState } from "~/store/Broker/loadHistory";
import { LoadsDetailsState } from "~/store/Broker/loadsDetails";
import { NotesDetailsState } from "~/store/Broker/notesDetails";
import { OpenLoadsDetailsState } from "~/store/Broker/openLoads";
import { QuotesDetailsState } from "~/store/Broker/quotes";
import { ShipmentsDetailsState } from "~/store/Broker/shipmentsDetails";
import { TopCarriersState } from "~/store/Broker/topCarriersDetails";
import { TopCustomersDetailsState } from "~/store/Broker/topCustomers";
import { YearlySummaryState } from "~/store/Broker/yearlySummary";
import { AccidentsState } from "~/store/accidents";
import { AlertState } from "~/store/alerts";
import { ApplicantsState } from "~/store/applicants";
import { BrokersDetailsState } from "~/store/brokers";
import { CarriersDetailsState } from "~/store/carriers";
import { ClientState } from "~/store/client";
import { CommonState } from "~/store/common";
import { CompanyState } from "~/store/company";
import { DevicesDetailsState } from "~/store/devices";
import { DispatchSummaryState } from "~/store/dispatch";
import { DocumentsDetailsState } from "~/store/documents";
import { DriverState } from "~/store/driver";
import { DriversDetailsState } from "~/store/driverBoard";
import { DrugTestState } from "~/store/drugTest";
import { GrossBoardDetailsState } from "~/store/grossBoard";
import { GrossFinancialSummaryState } from "~/store/grossFinancial";
import { IncidentRegistryDetailsState } from "~/store/incidentRegistry";
import { InspectionReportDetailsState } from "~/store/inspectionReport";
import { InspectionsDetailsState } from "~/store/inspections";
import { LoadDetailsState } from "~/store/loads";
import { LocationsDetailsState } from "~/store/locations";
import { OnboardState } from "~/store/onboard";
import { PermitsDetailsState } from "~/store/permits";
import { SafetyMetricsSummaryState } from "~/store/safetyMetrics";
import { ServicesDetailsState } from "~/store/services";
import { StopState } from "~/store/stops";
import { TrailerState } from "~/store/trailer";
import { TrainingState } from "~/store/training";
import { TruckState } from "~/store/truck";
import { VehiclesState } from "~/store/vehicles";
import { ViolationsState } from "~/store/violationsPoints";

export interface RootStoreState extends StoreState {
    accidents: AccidentsState;
    Accounting: {
        assetsDetails: AssetsDetailsState;
        assetTransactions: AssetTransactionsDetailsState;
        breakdownBrokerPending: BreakdownBrokerPaymentsDetailState;
        brokerMetricsDetails: BrokerMetricsDetailsState;
        brokerReviewsDetails: BrokerReviewsDetailsState;
        brokers: BrokersDetailsState;
        contactsDetails: ContactsDetailsState;
        drivers: DriversDetailsState;
        factoring: FactoringDetailsState;
        fuelReport: FuelReportsState;
        generateInvoice: GenerateInvoiceDetailsState;
        invoiceBoard: InvoiceBoardDetailsState;
        invoices: InvoicesDetailsState;
        mileageReport: MileageReportsState;
        operationalPayments: OperationalTransactionsDetailsState;
        payablePaymentsSummary: PayablePaymentSummaryState;
        payableSumary: PayableSummaryState;
        payrollFinancialSummary: PayrollFinancialSummaryState;
        payrollMetricsSummary: PayrollMetricsSummaryState;
        recievables: ReceivablesSummaryState;
        receivedPayments: ReceivedPaymentDetailsState;
        taskDetails: TaskDetailsState;
        tollReport: TollReportsState;
        vendorPayments: VendorPaymentsDetailsState;
        vendors: VendorsDetailsState;
    }
    alerts: AlertState;
    applicants: ApplicantsState;
    Broker: {
        brokersDetails: BrokersDetailsState;
        brokerSummary: BrokerSummaryState;
        carrierSalesLeadersDetails: CarrierSalesLeadersState;
        carriersDetails: CarriersDetailsState;
        contactsDetails: ContactsDetailsState;
        contractRates: ContractRatesDetailsState;
        customerSalesLeadersDetails: CustomerSalesLeadersState;
        customersDetails: CustomersDetailsState;
        docummentsDetails: DocumentsDetailsState;
        invoicingDetails: InvoicingDetailsState;
        loadHistory: LoadHistoryDetailsState;
        loadsDetails: LoadsDetailsState;
        notesDetails: NotesDetailsState;
        openLoads: OpenLoadsDetailsState;
        quotes: QuotesDetailsState;
        shipmentsDetails: ShipmentsDetailsState;
        topCarriersDetails: TopCarriersState;
        topCustomers: TopCustomersDetailsState;
        yearlySummary: YearlySummaryState;
    }
    brokers: BrokersDetailsState;
    carriers: CarriersDetailsState;
    client: ClientState;
    common: CommonState;
    company: CompanyState;
    devices: DevicesDetailsState;
    dispatch: DispatchSummaryState;
    documents: DocumentsDetailsState;
    driver: DriverState;
    driverBoard: DriversDetailsState;
    drugTest: DrugTestState;
    grossBoard: GrossBoardDetailsState;
    grossFinancial: GrossFinancialSummaryState;
    incidentRegistry: IncidentRegistryDetailsState;
    inspectionReport: InspectionReportDetailsState;
    inspections: InspectionsDetailsState;
    loads: LoadDetailsState;
    locations: LocationsDetailsState;
    onboard: OnboardState;
    permits: PermitsDetailsState;
    safetyMetrics: SafetyMetricsSummaryState;
    services: ServicesDetailsState;
    stops: StopState;
    trailer: TrailerState;
    training: TrainingState;
    truck: TruckState;
    vehicles: VehiclesState;
    violationsDetails: ViolationsState;
    violationsPoints: ViolationsState;
}